mannequinIndumentaria/grupo_3_mannequin

public/stylesheets/styleForm.css, views/index.ejs, views/partials/head.ejs, views/partials/headRegister.ejs, views/partials/registerF.ejs, views/partials/registerForm.ejs, views/register.ejs
=> Formularios Log in y Registro

controllers/registerController.js, routes/register.js, views/registerFormCompleto.ejs
=> ruteo actualizado

public/stylesheets/styleNav.css, views/partials/banner.ejs, views/partials/header.ejs
=> nav bar  casi terminado

package-lock.json, public/stylesheets/styleFooter.css, views/partials/footer.ejs, views/partials/header.ejs
=> footer responsive

public/stylesheets/styleNav.css, views/partials/header.ejs
=> header responsive

public/stylesheets/styleForm.css, public/stylesheets/styleNav.css, views/partials/header.ejs, views/partials/registerForm.ejs
=> cambios clari

public/stylesheets/categories.css, views/partials/productsWrapper.ejs
Se agrega el vinculo para acceder a detalleProducto desde producto, y para acceder a carrito desde Producto.
=> fix vinculo

public/stylesheets/styleForm.css, public/stylesheets/styleIndex.css, public/stylesheets/styleNav.css, views/cargaArticulo.ejs, views/carrito.ejs, views/categories.ejs, views/detalleProducto.ejs, views/index.ejs, views/partials/head.ejs, views/partials/registerForm.ejs, views/register.ejs
Se implementa que el menu se oculte en el window scroll, se agrega un nuevo div llamado contenido, porque era necesario bajar el contenido. Falta arreglar el alto con los @media. Tambien se acomodaron algunas estructuras.
=> Se implementa menu ocultable

controllers/categoriesController.js, data/categories.json, views/partials/navCategories.ejs
Creación JSON Categories con SubCategories
Tratamiento en Vista
=> JSON-Categories

controllers/indexController.js, routes/index.js
=> search incompleto

controllers/registerController.js, views/partials/registerForm.ejs
=> login terminado y anda

controllers/indexController.js, controllers/registerController.js, services/carrouselNS.js, services/carrouselS.js, views/partials/registerForm.ejs
=> cambios NO TOCAR

controllers/detalleProductoController.js, controllers/indexController.js, routes/detalleProducto.js, views/detalleProducto.ejs
Actualización Controller y Router detalleProducto
=> Nico detalle producto

controllers/carritoController.js
=> carrousel act en carrito

public/stylesheets/carrito.css, views/carrito.ejs
=> mod carrito tamano fotos

controllers/indexController.js, data/subscribers.json, routes/index.js, views/partials/footer.ejs
=> suscribe listo

app.js, controllers/crudIndexController.js, package-lock.json, package.json, routes/crudIndex.js, views/crudIndex.ejs, views/editarArticulo.ejs, views/partials/headerCRUD.ejs
Arme listados del crud(falta estilo), y modificar (en curso).
=> sumo crudIndex y editarArticulo

controllers/registerController.js, package-lock.json, package.json, routes/register.js, views/partials/registerFormCompleto.ejs
=> validaciones con check

app.js, controllers/registerController.js, middlewares/usuarioLogueado.js, package-lock.json, package.json, routes/register.js, views/partials/registerForm.ejs
=> session and cookies inc

public/stylesheets/styleProfile.css, views/partials/head.ejs, views/partials/profileForm.ejs
=> profile completo!!

app.js, controllers/indexController.js, controllers/registerController.js, data/users.json, routes/register.js, views/partials/header.ejs, views/partials/profileForm.ejs
=> session lo q hay

controllers/profileController.js, views/partials/header.ejs
habia un problema en la estructura del dropdown del menu de usuario.
=> nueva estructura menu user

controllers/categoriesController.js, controllers/indexController.js, data/mannequin_db1.sql, middlewares/usuarioLogueado.js, routes/categories.js, routes/index.js
se corrige la sesion para que este consistente en todas las rutas. se implementa middleware. (Todo esto con Alexandra, Clara, Emma y Nico).
Subo nueva db que se llama mannequin_db1, esta contiene la nueva estructura analizada en equipo.
=> fix session y nueva db

controllers/categoriesController.js, controllers/indexController.js, views/categories.ejs, views/partials/pagination.ejs
se comenta el paginado, hasta que se implemente bien
=> se corrigen errores en search y categories

controllers/crudProductController.js, controllers/crudUserController.js, routes/crudIndex.js, views/crudProduct.ejs, views/crudUsers.ejs
se agrega busqueda a crud de productos y de usuarios
=> add search

data/scripts/mannequin_db3.sql
=> solucion subscribers

app.js, controllers/api/usersController.js, middlewares/usuarioLogueado.js, public/js/validacionForm.js, routes/api/users.js, routes/index.js, routes/profile.js, routes/register.js, views/partials/registerFormCompleto.ejs
creamos api de usuarios, y agregamos validaciones
=> validacion de email, y otros en register

controllers/api/productsController.js, controllers/carritoController.js, controllers/categoriesController.js, routes/api/products.js, routes/carrito.js, routes/categories.js, routes/detalleProducto.js, views/partials/header.ejs, views/partials/productsWrapper.ejs
se crea endpoint de products para agregar un item al carrito del usuario.
=> addBag button

controllers/api/productsController.js, routes/api/products.js, services/menu.js, views/carrito.ejs, views/detalleProducto.ejs, views/partials/productsWrapper.ejs
agruegue talles a product wrapper y mejore la obtencion de talles
=> fixes varios

controllers/crudCouponController.js, data/Scripts/mannequin_db_DATABASE_script.sql, database/models/Discount_coupon.js, middlewares/adminLogueado.js, public/js/config.js, public/js/funciones.js, routes/crudIndex.js, views/cargaCupon.ejs, views/carrito.ejs, views/crudCoupon.ejs, views/partials/headerCRUD.ejs
=> add cupones

app.js, controllers/api/categoriesController.js, controllers/api/productsController.js, routes/api/categories.js, routes/api/products.js
=> Api controller categories

controllers/categoriesController.js, routes/categories.js, views/partials/header.ejs
se crea el filtro de favoritos
=> filtro de listado

public/js/latido.js, views/carrito.ejs, views/detalleProducto.ejs, views/partials/header.ejs, views/partials/productsWrapper.ejs
se aplica favoritos en carrito. Se crea funcion para que titile el carrito y el corazon al agregar un item
=> fixes favoritos

controllers/api/productsController.js, controllers/api/usersController.js, public/js/funciones.js, routes/api/products.js, routes/api/users.js, views/carrito.ejs
se implementa logica de cupones y se fixean problemas de totales
=> fixes carrito
